name: "[Publish] Medium Article"
# uses: https://github.com/philips-software/post-to-medium-action

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Article folder name: blog/<THIS_FOLDER_NAME>/index.medium'
        required: true
        type: string
      title:
        description: 'Article Title'
        required: true
        type: string
      tags:
        description: 'List of tags (eg. "tag1,tag2")'
        required: true
        type: string
        

jobs:
  post-to-medium:
    name: Post to Medium
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.6.0
        with:
          integration_token: "${{ secrets.MEDIUM_TOKEN }}"
          file: "content/${{ inputs.folder }}/index.medium"
          content_format: "markdown"
          notify_followers: "false"
          tags: "${{ inputs.tags }}"
          title: ${{ inputs.title }}
          license: "all-rights-reserved"
          publish_status: "public"